apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: todo-api-gitops
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Akshaykumar-Bawane/GitOps-Bullet-5.git
    targetRevision: HEAD
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: todo-api
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
